### ISSUE TITLE
ETP-195 : Payment Netting on Cancel Replace marking invoices as paid

### ISSUE THREAD

**Issue by Amar-Etendo** [etendosoftware/etendo_core#454]
**Error's description**

The cancel and replace functionality is marking the payment plan and sales invoice total paid even though no payment has been applied to either Sales Order or Sales Invoiced.

**Steps to reproduce the error**

1. Create and Book a Sales Order without applying any payment.
2. Partially or Fully Ship the Sales Order.
3. Partially or Fully Invoice the Sales Order.
4. Initiate the cancel and replace on the Sales Order, modify the quantity or amount on one of the lines, which causes a change in the order net amount.

After processing the cancel and replace, review the Payment Plan tab in both the Sales Order and Invoice windows. It incorrectly shows that payment has been received, despite no payment being made.
Please refer the attached video for the steps to reproduce the issue.
[ESD-681_Issue_Steps_Reproduced.webm](https://github.com/user-attachments/assets/c4ed929e-900d-45e0-a13b-26b819bbdde2)

**Required Configurations (if necessary)**
Enable the Enable Cancel and Replace preference with value as Y(please refer attached video as well as below screenshot:

![image](https://github.com/user-attachments/assets/4fe0bcd8-6c3e-41ac-909b-9e593b50f84e)

**Expected behavior**
There should not be any payment received after executing cancel and replace for the order.

**Affected Version** 

¿ Latest/Specific ?

Version number: 23.4.0

Solution Design (optional)

**Other test cases**

  Given:

  When:

  Then:

**Comment by valeg-etendo** [comment]
By @jortolanosmf 

This is expected system behavior and does not represent a problem since when performing a cancel and replace the system creates the following sequence of orders:

![image](https://github.com/user-attachments/assets/da329139-9555-4064-bd3d-1bc1a58639ee)
Orders generated::

- 1000380: Original order, the payment plan appears fully paid because it has been cancelled and closed.

![image](https://github.com/user-attachments/assets/d12a7ac3-3cd1-4852-9612-15df0fcb4723)

- 1000380*R*: Reverse order, here the amount paid in 1000380 is returned, can be seen below:

![image](https://github.com/user-attachments/assets/9eaeb5f8-f3d0-477a-949b-0cefcc31f5a5)

- 1000380-1: New order, which allows you to add quantities from existing lines or from new lines. It also inherits the payment plan with what has been paid in 1000380, for this specific example everything still remains to be paid..

![image](https://github.com/user-attachments/assets/52998827-9e25-4b9a-b361-66659c7d8225)

Regarding invoices, the behavior is as expected since the functionality has had to cancel order 1000380 and its associated invoice reflects the same behavior in its payments.

![image](https://github.com/user-attachments/assets/fec9253f-e1e4-4130-bdf0-470cee2c6189)

Due to this we confirm that there is no error in the system nor at the accounting level since the scope of the functionality only includes the cancellation of the original order 1000380, which results in the invoice showing the entire payment plan as paid. From here it is the user who must do what is necessary to complete the operation.
