### ISSUE TITLE
ETP-310: Incorrect error return processing in payment. When posting a payment in it gives an incorrect error if the configurations are not correct and there are 2 general ledger

### ISSUE THREAD

**Issue by juanfunes1996** [etendosoftware/etendo_core#467]
# Error's description
Incorrect error return processing in payment. When posting a payment in it gives an incorrect error if the configurations are not correct and there are 2 general ledger. If a payment method has in the "Upon Receipt Use" field a reference to an empty field in the financial account settings, when posting a payment in, it says document disabled error, which is not correct.

 # Steps to reproduce the error

1. Create a payment from a registered sales order.
2. The financial account related to the payment, in the payment method related to the payment in, in the field "Upon Receipt Use", select "In Transit Payment Account". See attached image
3. In the accounting configuration tab of the financial account, there must be 2 general ledger records and the "Cleared Payment Account" field must be empty in 2 general ledger records.
4. Posting the payment in will give a document disabled error.

https://github.com/user-attachments/assets/86abae7c-df51-4b4d-bb24-30dda808386a

 # Expected behavior
It should give a descriptive error. Reporting that there is no information in the field

 # Affected Version
Etendo Core: 24.2.6

 # Solution Design (optional)

 # Other test cases
 **Given:**
 **When:**
 **Then:**

**Comment by ivanrobledofutit** [comment]
Valeria and I analyzed the bug and how it was being reproduced. During the process, we realized that it wasn’t a bug but rather a configuration issue. We reached this conclusion by observing that when configuring the financial account, if the payment method in "Upon Receipt Use" is anything other than "Cleared Payment Account," the system works correctly. However, if "Cleared Payment Account" is selected, it must first be configured in "Accounting Configuration," specifically in the "Payment In" section. Therefore, we concluded that this is a configuration issue because the user, when selecting "Cleared Payment Account," should be aware that it also needs to be set up in "Accounting Configuration."
